Update eslint to 8.36.0
iTwin/eslint-plugin pull request #12
Opened 2023-03-23 13:48 UTC by yashincontrol

After the PRs on appui (https://github.com/iTwin/appui/pull/216) and presentation (https://github.com/iTwin/presentation/pull/89) are merged, there should be no issues with this update. Here is nightman for reference: https://github.com/iTwin/nightman/actions/runs/4500732451/jobs/7920240470#step:16:110

2023-03-23 13:54 UTC, ben-polinsky approved these changes

2023-03-23 14:50 UTC, aruniverse requested changes
beachball change?

2023-03-23 15:21 UTC, aruniverse approved these changes

2023-03-23 17:05 UTC, aruniverse commented on change/@itwin-eslint-plugin-9e5d024e-f1c6-4768-b61b-f5eacd8a2d26.json
> +  "type": "minor",
when we're ready to do an actual release itll be major

2023-03-23 17:07 UTC, paulius-valiunas commented on change/@itwin-eslint-plugin-9e5d024e-f1c6-4768-b61b-f5eacd8a2d26.json
> +  "type": "minor",
but the whole point of beachball is to track which changes require a major bump. You shouldn't manually override the bump type, this file is what will define which version gets bumped

2023-03-23 17:09 UTC, aruniverse commented on change/@itwin-eslint-plugin-9e5d024e-f1c6-4768-b61b-f5eacd8a2d26.json
> +  "type": "minor",
fair.

@yashincontrol change this to major

2023-03-23 17:36 UTC, yashincontrol commented on change/@itwin-eslint-plugin-9e5d024e-f1c6-4768-b61b-f5eacd8a2d26.json
> +  "type": "minor",
Okay

2023-03-24 09:13 UTC, paulius-valiunas approved these changes

2023-03-24 12:21 UTC, yashincontrol commented
Update: The above PRs have been merged and nightman looks good https://github.com/iTwin/nightman/actions/runs/4510910957/jobs/7942425243

2023-03-24 13:10 UTC, merged